/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salarycalculator;

/**
 *
 * @author tolaotesanya
 */
public class MySalaryGUI extends javax.swing.JFrame {

    /**
     * Creates new form MySalaryGUI
     */
    SalaryInterface sal;
    public MySalaryGUI() {
        initComponents();
        sal = new MySalary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        grossSalary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        taxDue = new javax.swing.JButton();
        netSalary = new javax.swing.JButton();
        monthlySalary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Salary Calculator"));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Yearly Gross Income");

        taxDue.setText("Tax Due");
        taxDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxDueActionPerformed(evt);
            }
        });

        netSalary.setText("Net Income");
        netSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSalaryActionPerformed(evt);
            }
        });

        monthlySalary.setText("Monthly Net Income");
        monthlySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlySalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exit)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(taxDue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(netSalary)
                .addGap(45, 45, 45)
                .addComponent(monthlySalary)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(grossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxDue)
                    .addComponent(netSalary)
                    .addComponent(monthlySalary))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void taxDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxDueActionPerformed
            int grossSal = Integer.parseInt(grossSalary.getText());
            int twentyone;
            int fortyone;
 
            double tOP = 0.20;
            double fOP = 0.40;
            int earnedGross = 33800;
            int higherTaxGross = grossSal - earnedGross;
 
            double twenty = (double) earnedGross * tOP;// typecast to double
            double forty = (double) higherTaxGross * fOP;//typecast to double
            int taxDue = (int) twenty + (int)forty;
            jTextArea1.append("Thank you for using TSalary Calculator\n\n");
            jTextArea1.append("The Tax amount due on " + grossSal + " is: " + taxDue +"\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_taxDueActionPerformed

    private void netSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSalaryActionPerformed
            int grossSal = Integer.parseInt(grossSalary.getText());
            int twentyone;
            int fortyone;
 
            double tOP = 0.20;
            double fOP = 0.40;
            int earnedGross = 33800;
            int higherTaxGross = grossSal - earnedGross;
 
            double twentyOne = (double) earnedGross * tOP;// typecast to double
            double fortyOne = (double) higherTaxGross * fOP;//typecast to double
            int taxDue = (int) twentyOne + (int)fortyOne;
 
            int netSal = grossSal - taxDue;
            
            jTextArea1.append("The Net Income is: " + grossSal + " - " + taxDue + " = " + netSal + "\n");
            

        // TODO add your handling code here:
    }//GEN-LAST:event_netSalaryActionPerformed

    private void monthlySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlySalaryActionPerformed
            int grossSal = Integer.parseInt(grossSalary.getText());
            int twentyone;
            int fortyone;
 
            double tOP = 0.20;
            double fOP = 0.40;
            int earnedGross = 33800;
            int higherTaxGross = grossSal - earnedGross;
 
            double twentyOne = (double) earnedGross * tOP;// typecast to double
            double fortyOne = (double) higherTaxGross * fOP;//typecast to double
            int taxDue = (int) twentyOne + (int)fortyOne;
 
            int netSal = grossSal - taxDue;
 
            int monthlygrossSal = grossSal / 12;
            int monthlynetSal = netSal / 12;
            
            jTextArea1.append("Your monthly Net Income is: " + monthlynetSal + "\n\n");

        // TODO add your handling code here:
    }//GEN-LAST:event_monthlySalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MySalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MySalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MySalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MySalaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTextField grossSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton monthlySalary;
    private javax.swing.JButton netSalary;
    private javax.swing.JButton taxDue;
    // End of variables declaration//GEN-END:variables
}
